### ISSUE TITLE
There's a duplicate Add here, and the problem is solved when I remove one of them.

### ISSUE THREAD

**Issue by xiejunsheng03** [livekit/client-sdk-unity#1]
![db5ba46adfed5c1a99cb7a819117240](https://github.com/livekit/client-sdk-unity/assets/132739744/aa548cfb-0878-477e-99b0-f1f77e9f8514)

**Comment by theomonnom** [comment]
Is it only happening when someone joins the room?

**Comment by xiejunsheng03** [comment]
Link a room with a human presence, other scenes I haven't tried yet
