### ISSUE TITLE
Error when building on Windows

### ISSUE THREAD

**Issue by AdamBuchweitz** [livekit/client-sdk-unity#10]
After adding LiveKit SDK to my project, I can no longer build due to the following error:

`Library\PackageCache\io.livekit.livekit-sdk@60ae9e2e41\Runtime\Scripts\Internal\FFIClient.cs(69,13):
error CS0176Member 'FfiClient.Initialize()' cannot be accessed with an instance reference; qualify it with a type name instead`

**Comment by ashkan-saeedi-mazdeh** [comment]
I don't know if it helps guys or not but change line 69 to this 
![image](https://github.com/livekit/client-sdk-unity/assets/5682459/b0b002ae-8ff8-4c42-8da6-93b0f98e8322)

`FfiClient.Initialize();` instand of `Instace.Initialize()`

**Comment by cloudwebrtc** [comment]
Fixed in the latest version
