### ISSUE TITLE
How stable is the unity android livekit SDK as of now? Any plans on iOS support?

### ISSUE THREAD

**Issue by sadeepdarshana** [livekit/client-sdk-unity#33]
I'm planning to build a 2D unity app for mobile (initially android) where people can create audio only rooms (of around 10 participants each). All of them can communicate at once.

There would be a number of such rooms at a given time.

1. How stable is the unity android SDK as of now for this use case? 
2. Any plans on iOS support?

**Comment by davidzhao** [comment]
Android is pretty stable now! Folks are starting to use it in Unity apps.

We do plan on supporting iOS as well. Development has not started though.

**Comment by cloudwebrtc** [comment]
Yeah, we have started investigating how to run the unity sdk on iOS, and I believe it will be supported within a week or two.
